omd-nagios:
    container_name: omd-nagios
    image: consol/omd-labs-ubuntu-sakuli:github-204-docker-cloud
    ports:
    - 8043:443
    - 4730:4730
    cpu_quota: 65000
    environment:
    - TZ=Europe/Berlin
    volumes:
    - /etc/localtime:/etc/localtime
    - ./omd_ansible_drop-in_role/:/root/ansible_omd/dropin_role
