#### POD config (run one time)
apiVersion: v1
kind: Namespace
metadata:
  name: sakuli
---
apiVersion: v1
kind: Pod
metadata:
  namespace: sakuli
  labels:
    application: selenium-ui-test
  name: selenium-ui-test
spec:
  ### ensure that the pod won't start again
  restartPolicy: Never
  dnsPolicy: ClusterFirst
  terminationGracePeriodSeconds: 5
  containers:
  - name: selenium-ui-test
    image: toschneck/sakuli-se-example
    imagePullPolicy: Always
      #    args:
      ### make normal UI startup to connect via: oc rsh <pod-name> bash
      #- '--tail-log'
      ### run in chrome
      # - 'run'
      # - '/headless/sakuli/test'
      # - '-browser'
      # - 'chrome'
      ### set e.g. debug level
      #- '-D'
    #- 'log.level.sakuli=DEBUG'
    ### checks that vnc server is up and running
    livenessProbe:
      tcpSocket:
        port: 5901
      initialDelaySeconds: 5
      timeoutSeconds: 5
    ### checks if http-vnc connection is working
    readinessProbe:
      httpGet:
        path: /
        port: 6901
        scheme: HTTP
      initialDelaySeconds: 5
      timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: selenium-ui-test
  namespace: sakuli
  name: selenium-ui-test
spec:
  externalName: selenium-ui-test
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 80
    targetPort: 6901
  selector:
    application: selenium-ui-test
  type: LoadBalancer