# Run test in two separated environments: Ubuntu/Firefox and CentOS/Chrome

sakuli_test_ubuntu_firefox:
  image: consol/sakuli-ubuntu-xfce
  volumes:
  - ./example_xfce:/opt/test
  ports:
  - 5911:5901
  - 6911:6901
  command: ["run /opt/test"]

sakuli_test_centos_chrome:
  image: consol/sakuli-centos-xfce
  volumes:
  - ./example_xfce:/opt/test
  ports:
  - 5912:5901
  - 6912:6901
  command: ["run /opt/test -browser chrome"]