apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - imageName: toschneck/sakuli-se-example
    docker:
      dockerfilePath: Dockerfile.skaffold

deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml

profiles:
# "travis-ci" profile is used to build the images without
# pushing them.
- name: local
  build:
    local:
      skipPush: true
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
#  - name: gcb
#    build:
#      googleCloudBuild:
#        projectId: loodse-sc-test
#        diskSizeGb: 300
#        machineType: "N1_HIGHCPU_32"

### load test profile, run with:
###    skaffold run --profile=loadtest
#  - name: loadtest
#    build:
#      artifacts:
#      - imageName: gcr.io/loodse-sc-test/loadgenerator
#        workspace: src/loadgenerator
#    deploy:
#      kubectl:
#        manifests:
#        - ./kubernetes-manifests/test/**.yaml
