omd-nagios:
    container_name: omd-nagios
#    TODO TS: check if still working with grafana
    image: consol/omd-labs-centos-sakuli:grafana
    #runtime data backup
#    image: toschneck/omd-nagios-demo:jug-saxony-day
    ports:
    - 8043:443
    cpu_quota: 65000
    environment:
    - TZ=Europe/Berlin
    volumes:
    - /etc/localtime:/etc/localtime
    - ./ansible_dropin/:/root/ansible_dropin
