omd-nagios:
    container_name: omd-nagios
    image: consol/omd-labs-centos-sakuli:grafana
    ports:
    - 8043:443
    - 4730:4730
    cpu_quota: 65000
    environment:
    - TZ=Europe/Berlin
    volumes:
    - ./omd_ansible_drop_in/:/root/ansible_dropin
