sakuli:
    container_name: sakulie2e
    image: consol/sakuli-ubuntu-xfce:dev
    volumes:
    - ./sakuli_docker_test:/headless/sakuli_docker_test
    - ./sahi_ff_profile_template:/headless/sakuli/sahi/config/ff_profile_template
    - ./sahi_certs:/headless/sakuli/sahi/userdata/certs
    ports:
    - "5901:5901"
    - "6901:6901"
    command: "run /headless/sakuli_docker_test -loop 1"
    links:
    - omdlabs:omd

omdlabs:
    container_name: omdlabs
    image: consol/omd-labs-ubuntu-sakuli:dev
    volumes:
    - ./omd_ansible_dropin_role/:/root/ansible_dropin
    ports:
    - "8443:443"
